# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddVendorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_addVendorDialog(object):
    def setupUi(self, addVendorDialog):
        addVendorDialog.setObjectName("addVendorDialog")
        addVendorDialog.resize(600, 548)
        font = QtGui.QFont()
        font.setPointSize(11)
        addVendorDialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(addVendorDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(addVendorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(addVendorDialog)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setSpacing(20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.name_validation_label = QtWidgets.QLabel(self.frame)
        self.name_validation_label.setObjectName("name_validation_label")
        self.gridLayout_2.addWidget(self.name_validation_label, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.baseUrlEdit = QtWidgets.QLineEdit(self.frame)
        self.baseUrlEdit.setObjectName("baseUrlEdit")
        self.gridLayout_2.addWidget(self.baseUrlEdit, 2, 1, 1, 1)
        self.nameEdit = QtWidgets.QLineEdit(self.frame)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout_2.addWidget(self.nameEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 9, 0, 1, 1, QtCore.Qt.AlignTop)
        self.companiesEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.companiesEdit.setObjectName("companiesEdit")
        self.gridLayout_2.addWidget(self.companiesEdit, 10, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 7, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 10, 0, 1, 1, QtCore.Qt.AlignTop)
        self.customerIdEdit = QtWidgets.QLineEdit(self.frame)
        self.customerIdEdit.setObjectName("customerIdEdit")
        self.gridLayout_2.addWidget(self.customerIdEdit, 4, 1, 1, 1)
        self.apiKeyEdit = QtWidgets.QLineEdit(self.frame)
        self.apiKeyEdit.setObjectName("apiKeyEdit")
        self.gridLayout_2.addWidget(self.apiKeyEdit, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 6, 0, 1, 1)
        self.platformEdit = QtWidgets.QLineEdit(self.frame)
        self.platformEdit.setObjectName("platformEdit")
        self.gridLayout_2.addWidget(self.platformEdit, 7, 1, 1, 1)
        self.descriptionEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.gridLayout_2.addWidget(self.descriptionEdit, 9, 1, 1, 1)
        self.requestorIdEdit = QtWidgets.QLineEdit(self.frame)
        self.requestorIdEdit.setObjectName("requestorIdEdit")
        self.gridLayout_2.addWidget(self.requestorIdEdit, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 8, 0, 1, 1)
        self.local_only_check_box = QtWidgets.QCheckBox(self.frame)
        self.local_only_check_box.setText("")
        self.local_only_check_box.setObjectName("local_only_check_box")
        self.gridLayout_2.addWidget(self.local_only_check_box, 8, 1, 1, 1)
        self.url_validation_label = QtWidgets.QLabel(self.frame)
        self.url_validation_label.setObjectName("url_validation_label")
        self.gridLayout_2.addWidget(self.url_validation_label, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(addVendorDialog)
        QtCore.QMetaObject.connectSlotsByName(addVendorDialog)

    def retranslateUi(self, addVendorDialog):
        _translate = QtCore.QCoreApplication.translate
        addVendorDialog.setWindowTitle(_translate("addVendorDialog", "Add Vendor"))
        self.name_validation_label.setText(_translate("addVendorDialog", "Validation label"))
        self.label.setText(_translate("addVendorDialog", "Name"))
        self.label_2.setText(_translate("addVendorDialog", "Customer ID"))
        self.label_3.setText(_translate("addVendorDialog", "Base URL"))
        self.label_7.setText(_translate("addVendorDialog", "Description"))
        self.label_6.setText(_translate("addVendorDialog", "Platform (optional)"))
        self.label_9.setText(_translate("addVendorDialog", "External Companies"))
        self.label_5.setText(_translate("addVendorDialog", "API Key (optional)"))
        self.label_4.setText(_translate("addVendorDialog", "Requestor ID (oprtional)"))
        self.label_8.setText(_translate("addVendorDialog", "Local Only Vendor"))
        self.url_validation_label.setText(_translate("addVendorDialog", "Validation label"))

