# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CostsTab.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_costs_tab(object):
    def setupUi(self, costs_tab):
        costs_tab.setObjectName("costs_tab")
        costs_tab.resize(898, 671)
        self.verticalLayout = QtWidgets.QVBoxLayout(costs_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.costs_parameters_frame = QtWidgets.QFrame(costs_tab)
        self.costs_parameters_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.costs_parameters_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.costs_parameters_frame.setObjectName("costs_parameters_frame")
        self.formLayout_3 = QtWidgets.QFormLayout(self.costs_parameters_frame)
        self.formLayout_3.setObjectName("formLayout_3")
        self.costs_report_parameter_label = QtWidgets.QLabel(self.costs_parameters_frame)
        self.costs_report_parameter_label.setObjectName("costs_report_parameter_label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.costs_report_parameter_label)
        self.costs_report_parameter_combobox = QtWidgets.QComboBox(self.costs_parameters_frame)
        self.costs_report_parameter_combobox.setObjectName("costs_report_parameter_combobox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.costs_report_parameter_combobox)
        self.costs_vendor_parameter_label = QtWidgets.QLabel(self.costs_parameters_frame)
        self.costs_vendor_parameter_label.setObjectName("costs_vendor_parameter_label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.costs_vendor_parameter_label)
        self.costs_vendor_parameter_combobox = QtWidgets.QComboBox(self.costs_parameters_frame)
        self.costs_vendor_parameter_combobox.setObjectName("costs_vendor_parameter_combobox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.costs_vendor_parameter_combobox)
        self.costs_year_parameter_label = QtWidgets.QLabel(self.costs_parameters_frame)
        self.costs_year_parameter_label.setObjectName("costs_year_parameter_label")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.costs_year_parameter_label)
        self.costs_year_parameter_dateedit = QtWidgets.QDateEdit(self.costs_parameters_frame)
        self.costs_year_parameter_dateedit.setObjectName("costs_year_parameter_dateedit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.costs_year_parameter_dateedit)
        self.costs_name_parameter_label = QtWidgets.QLabel(self.costs_parameters_frame)
        self.costs_name_parameter_label.setObjectName("costs_name_parameter_label")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.costs_name_parameter_label)
        self.costs_name_parameter_combobox = QtWidgets.QComboBox(self.costs_parameters_frame)
        self.costs_name_parameter_combobox.setEditable(True)
        self.costs_name_parameter_combobox.setObjectName("costs_name_parameter_combobox")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.costs_name_parameter_combobox)
        self.verticalLayout.addWidget(self.costs_parameters_frame)
        self.costs_values_frame = QtWidgets.QFrame(costs_tab)
        self.costs_values_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.costs_values_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.costs_values_frame.setObjectName("costs_values_frame")
        self.formLayout = QtWidgets.QFormLayout(self.costs_values_frame)
        self.formLayout.setObjectName("formLayout")
        self.costs_cost_in_original_currency_label = QtWidgets.QLabel(self.costs_values_frame)
        self.costs_cost_in_original_currency_label.setObjectName("costs_cost_in_original_currency_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.costs_cost_in_original_currency_label)
        self.costs_original_currency_label = QtWidgets.QLabel(self.costs_values_frame)
        self.costs_original_currency_label.setObjectName("costs_original_currency_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.costs_original_currency_label)
        self.costs_original_currency_value_combobox = QtWidgets.QComboBox(self.costs_values_frame)
        self.costs_original_currency_value_combobox.setEnabled(False)
        self.costs_original_currency_value_combobox.setEditable(True)
        self.costs_original_currency_value_combobox.setObjectName("costs_original_currency_value_combobox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.costs_original_currency_value_combobox)
        self.costs_cost_in_local_currency_label = QtWidgets.QLabel(self.costs_values_frame)
        self.costs_cost_in_local_currency_label.setObjectName("costs_cost_in_local_currency_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.costs_cost_in_local_currency_label)
        self.costs_cost_in_local_currency_with_tax_label = QtWidgets.QLabel(self.costs_values_frame)
        self.costs_cost_in_local_currency_with_tax_label.setObjectName("costs_cost_in_local_currency_with_tax_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.costs_cost_in_local_currency_with_tax_label)
        self.costs_cost_in_original_currency_doublespinbox = QtWidgets.QDoubleSpinBox(self.costs_values_frame)
        self.costs_cost_in_original_currency_doublespinbox.setEnabled(False)
        self.costs_cost_in_original_currency_doublespinbox.setObjectName("costs_cost_in_original_currency_doublespinbox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.costs_cost_in_original_currency_doublespinbox)
        self.costs_cost_in_local_currency_doublespinbox = QtWidgets.QDoubleSpinBox(self.costs_values_frame)
        self.costs_cost_in_local_currency_doublespinbox.setEnabled(False)
        self.costs_cost_in_local_currency_doublespinbox.setObjectName("costs_cost_in_local_currency_doublespinbox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.costs_cost_in_local_currency_doublespinbox)
        self.costs_cost_in_local_currency_with_tax_doublespinbox = QtWidgets.QDoubleSpinBox(self.costs_values_frame)
        self.costs_cost_in_local_currency_with_tax_doublespinbox.setEnabled(False)
        self.costs_cost_in_local_currency_with_tax_doublespinbox.setObjectName("costs_cost_in_local_currency_with_tax_doublespinbox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.costs_cost_in_local_currency_with_tax_doublespinbox)
        self.verticalLayout.addWidget(self.costs_values_frame)
        self.costs_control_frame = QtWidgets.QFrame(costs_tab)
        self.costs_control_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.costs_control_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.costs_control_frame.setObjectName("costs_control_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.costs_control_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.costs_clear_button = QtWidgets.QPushButton(self.costs_control_frame)
        self.costs_clear_button.setObjectName("costs_clear_button")
        self.gridLayout.addWidget(self.costs_clear_button, 0, 2, 1, 1)
        self.costs_load_button = QtWidgets.QPushButton(self.costs_control_frame)
        self.costs_load_button.setObjectName("costs_load_button")
        self.gridLayout.addWidget(self.costs_load_button, 0, 1, 1, 1)
        self.costs_insert_button = QtWidgets.QPushButton(self.costs_control_frame)
        self.costs_insert_button.setObjectName("costs_insert_button")
        self.gridLayout.addWidget(self.costs_insert_button, 0, 3, 1, 1)
        self.costs_import_costs_button = QtWidgets.QPushButton(self.costs_control_frame)
        self.costs_import_costs_button.setObjectName("costs_import_costs_button")
        self.gridLayout.addWidget(self.costs_import_costs_button, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.costs_control_frame)

        self.retranslateUi(costs_tab)
        QtCore.QMetaObject.connectSlotsByName(costs_tab)

    def retranslateUi(self, costs_tab):
        _translate = QtCore.QCoreApplication.translate
        costs_tab.setWindowTitle(_translate("costs_tab", "Costs"))
        self.costs_report_parameter_label.setText(_translate("costs_tab", "Report"))
        self.costs_vendor_parameter_label.setText(_translate("costs_tab", "Vendor"))
        self.costs_year_parameter_label.setText(_translate("costs_tab", "Year"))
        self.costs_year_parameter_dateedit.setDisplayFormat(_translate("costs_tab", "yyyy"))
        self.costs_name_parameter_label.setText(_translate("costs_tab", "Name"))
        self.costs_cost_in_original_currency_label.setText(_translate("costs_tab", "Cost in Original Currency"))
        self.costs_original_currency_label.setText(_translate("costs_tab", "Original Currency"))
        self.costs_cost_in_local_currency_label.setText(_translate("costs_tab", "Cost in Local Currency"))
        self.costs_cost_in_local_currency_with_tax_label.setText(_translate("costs_tab", "Cost in Local Currency with Tax"))
        self.costs_clear_button.setText(_translate("costs_tab", "Clear"))
        self.costs_load_button.setText(_translate("costs_tab", "Load"))
        self.costs_insert_button.setText(_translate("costs_tab", "Insert"))
        self.costs_import_costs_button.setText(_translate("costs_tab", "Import Costs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    costs_tab = QtWidgets.QWidget()
    ui = Ui_costs_tab()
    ui.setupUi(costs_tab)
    costs_tab.show()
    sys.exit(app.exec_())

