# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FetchSpecialReportsTab.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fetch_special_reports_tab(object):
    def setupUi(self, fetch_special_reports_tab):
        fetch_special_reports_tab.setObjectName("fetch_special_reports_tab")
        fetch_special_reports_tab.resize(630, 317)
        self.horizontalLayout = QtWidgets.QHBoxLayout(fetch_special_reports_tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_26 = QtWidgets.QFrame(fetch_special_reports_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_26.sizePolicy().hasHeightForWidth())
        self.frame_26.setSizePolicy(sizePolicy)
        self.frame_26.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_21 = QtWidgets.QLabel(self.frame_26)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_15.addWidget(self.label_21)
        self.frame_32 = QtWidgets.QFrame(self.frame_26)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.select_vendors_button_special = QtWidgets.QPushButton(self.frame_32)
        self.select_vendors_button_special.setObjectName("select_vendors_button_special")
        self.horizontalLayout_9.addWidget(self.select_vendors_button_special)
        self.deselect_vendors_button_special = QtWidgets.QPushButton(self.frame_32)
        self.deselect_vendors_button_special.setObjectName("deselect_vendors_button_special")
        self.horizontalLayout_9.addWidget(self.deselect_vendors_button_special)
        self.verticalLayout_15.addWidget(self.frame_32)
        self.vendors_list_view_special = QtWidgets.QListView(self.frame_26)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.vendors_list_view_special.setFont(font)
        self.vendors_list_view_special.setAlternatingRowColors(True)
        self.vendors_list_view_special.setObjectName("vendors_list_view_special")
        self.verticalLayout_15.addWidget(self.vendors_list_view_special)
        self.horizontalLayout.addWidget(self.frame_26)
        self.frame_25 = QtWidgets.QFrame(fetch_special_reports_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_25.sizePolicy().hasHeightForWidth())
        self.frame_25.setSizePolicy(sizePolicy)
        self.frame_25.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_20 = QtWidgets.QLabel(self.frame_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_14.addWidget(self.label_20)
        self.frame_30 = QtWidgets.QFrame(self.frame_25)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setObjectName("frame_30")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_30)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tr_radio_button = QtWidgets.QRadioButton(self.frame_30)
        self.tr_radio_button.setObjectName("tr_radio_button")
        self.gridLayout_9.addWidget(self.tr_radio_button, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pr_radio_button = QtWidgets.QRadioButton(self.frame_30)
        self.pr_radio_button.setChecked(True)
        self.pr_radio_button.setObjectName("pr_radio_button")
        self.gridLayout_9.addWidget(self.pr_radio_button, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.dr_radio_button = QtWidgets.QRadioButton(self.frame_30)
        self.dr_radio_button.setObjectName("dr_radio_button")
        self.gridLayout_9.addWidget(self.dr_radio_button, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.ir_radio_button = QtWidgets.QRadioButton(self.frame_30)
        self.ir_radio_button.setObjectName("ir_radio_button")
        self.gridLayout_9.addWidget(self.ir_radio_button, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_14.addWidget(self.frame_30)
        self.horizontalLayout.addWidget(self.frame_25)
        self.frame_27 = QtWidgets.QFrame(fetch_special_reports_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_27.sizePolicy().hasHeightForWidth())
        self.frame_27.setSizePolicy(sizePolicy)
        self.frame_27.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_15 = QtWidgets.QFrame(self.frame_27)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_14 = QtWidgets.QLabel(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_22.addWidget(self.label_14)
        self.options_frame = QtWidgets.QFrame(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.options_frame.sizePolicy().hasHeightForWidth())
        self.options_frame.setSizePolicy(sizePolicy)
        self.options_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.options_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.options_frame.setObjectName("options_frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.options_frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_22.addWidget(self.options_frame)
        self.verticalLayout_16.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.frame_27)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_15 = QtWidgets.QLabel(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.frame_31 = QtWidgets.QFrame(self.frame_16)
        self.frame_31.setMaximumSize(QtCore.QSize(362, 230))
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setObjectName("frame_31")
        self.formLayout_5 = QtWidgets.QFormLayout(self.frame_31)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_5.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_5.setSpacing(20)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_22 = QtWidgets.QLabel(self.frame_31)
        self.label_22.setObjectName("label_22")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.label_23 = QtWidgets.QLabel(self.frame_31)
        self.label_23.setObjectName("label_23")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.begin_date_edit_special_year = QtWidgets.QDateEdit(self.frame_31)
        self.begin_date_edit_special_year.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.begin_date_edit_special_year.setObjectName("begin_date_edit_special_year")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.begin_date_edit_special_year)
        self.begin_date_edit_special_month = QtWidgets.QDateEdit(self.frame_31)
        self.begin_date_edit_special_month.setObjectName("begin_date_edit_special_month")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.begin_date_edit_special_month)
        self.end_date_edit_special_year = QtWidgets.QDateEdit(self.frame_31)
        self.end_date_edit_special_year.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.end_date_edit_special_year.setObjectName("end_date_edit_special_year")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.end_date_edit_special_year)
        self.end_date_edit_special_month = QtWidgets.QDateEdit(self.frame_31)
        self.end_date_edit_special_month.setObjectName("end_date_edit_special_month")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.end_date_edit_special_month)
        self.verticalLayout.addWidget(self.frame_31)
        self.verticalLayout_16.addWidget(self.frame_16)
        self.frame_29 = QtWidgets.QFrame(self.frame_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_29.sizePolicy().hasHeightForWidth())
        self.frame_29.setSizePolicy(sizePolicy)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setObjectName("frame_29")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_29)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.fetch_special_data_button = QtWidgets.QPushButton(self.frame_29)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fetch_special_data_button.sizePolicy().hasHeightForWidth())
        self.fetch_special_data_button.setSizePolicy(sizePolicy)
        self.fetch_special_data_button.setMaximumSize(QtCore.QSize(180, 16777215))
        self.fetch_special_data_button.setObjectName("fetch_special_data_button")
        self.gridLayout_8.addWidget(self.fetch_special_data_button, 0, 0, 1, 1)
        self.verticalLayout_16.addWidget(self.frame_29)
        self.horizontalLayout.addWidget(self.frame_27)

        self.retranslateUi(fetch_special_reports_tab)
        QtCore.QMetaObject.connectSlotsByName(fetch_special_reports_tab)

    def retranslateUi(self, fetch_special_reports_tab):
        _translate = QtCore.QCoreApplication.translate
        fetch_special_reports_tab.setWindowTitle(_translate("fetch_special_reports_tab", "Fetch Special Reports"))
        self.label_21.setText(_translate("fetch_special_reports_tab", "Select Vendors"))
        self.select_vendors_button_special.setText(_translate("fetch_special_reports_tab", "Select All"))
        self.deselect_vendors_button_special.setText(_translate("fetch_special_reports_tab", "Deselect All"))
        self.label_20.setText(_translate("fetch_special_reports_tab", "Select Report Type"))
        self.tr_radio_button.setText(_translate("fetch_special_reports_tab", "TR"))
        self.pr_radio_button.setText(_translate("fetch_special_reports_tab", "PR"))
        self.dr_radio_button.setText(_translate("fetch_special_reports_tab", "DR"))
        self.ir_radio_button.setText(_translate("fetch_special_reports_tab", "IR"))
        self.label_14.setText(_translate("fetch_special_reports_tab", "Options"))
        self.label_15.setText(_translate("fetch_special_reports_tab", "Date Range"))
        self.label_22.setText(_translate("fetch_special_reports_tab", "Begin Date"))
        self.label_23.setText(_translate("fetch_special_reports_tab", "End Date"))
        self.begin_date_edit_special_year.setDisplayFormat(_translate("fetch_special_reports_tab", "yyyy"))
        self.begin_date_edit_special_month.setDisplayFormat(_translate("fetch_special_reports_tab", "MM"))
        self.end_date_edit_special_year.setDisplayFormat(_translate("fetch_special_reports_tab", "yyyy"))
        self.end_date_edit_special_month.setDisplayFormat(_translate("fetch_special_reports_tab", "MM"))
        self.fetch_special_data_button.setText(_translate("fetch_special_reports_tab", "Fetch Special Report"))
