# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImportReportTab.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_import_report_tab(object):
    def setupUi(self, import_report_tab):
        import_report_tab.setObjectName("import_report_tab")
        import_report_tab.resize(630, 234)
        self.horizontalLayout = QtWidgets.QHBoxLayout(import_report_tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_21 = QtWidgets.QFrame(import_report_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_21.sizePolicy().hasHeightForWidth())
        self.frame_21.setSizePolicy(sizePolicy)
        self.frame_21.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_18 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_12.addWidget(self.label_18)
        self.vendors_list_view_import = QtWidgets.QListView(self.frame_21)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.vendors_list_view_import.setFont(font)
        self.vendors_list_view_import.setAlternatingRowColors(True)
        self.vendors_list_view_import.setObjectName("vendors_list_view_import")
        self.verticalLayout_12.addWidget(self.vendors_list_view_import)
        self.horizontalLayout.addWidget(self.frame_21)
        self.frame_20 = QtWidgets.QFrame(import_report_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_20.sizePolicy().hasHeightForWidth())
        self.frame_20.setSizePolicy(sizePolicy)
        self.frame_20.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_17 = QtWidgets.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_11.addWidget(self.label_17)
        self.report_types_list_view_import = QtWidgets.QListView(self.frame_20)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.report_types_list_view_import.setFont(font)
        self.report_types_list_view_import.setAlternatingRowColors(True)
        self.report_types_list_view_import.setObjectName("report_types_list_view_import")
        self.verticalLayout_11.addWidget(self.report_types_list_view_import)
        self.horizontalLayout.addWidget(self.frame_20)
        self.frame_22 = QtWidgets.QFrame(import_report_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_22.sizePolicy().hasHeightForWidth())
        self.frame_22.setSizePolicy(sizePolicy)
        self.frame_22.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_17 = QtWidgets.QFrame(self.frame_22)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_16 = QtWidgets.QLabel(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_24.addWidget(self.label_16)
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.label_19 = QtWidgets.QLabel(self.frame_19)
        self.label_19.setMinimumSize(QtCore.QSize(100, 0))
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_13.addWidget(self.label_19)
        self.report_year_date_edit = QtWidgets.QDateEdit(self.frame_19)
        self.report_year_date_edit.setObjectName("report_year_date_edit")
        self.horizontalLayout_13.addWidget(self.report_year_date_edit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.verticalLayout_24.addWidget(self.frame_19)
        self.verticalLayout_13.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.frame_22)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_36 = QtWidgets.QLabel(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_25.addWidget(self.label_36)
        self.frame_38 = QtWidgets.QFrame(self.frame_18)
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setObjectName("frame_38")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_38)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.selected_file_edit = QtWidgets.QLineEdit(self.frame_38)
        self.selected_file_edit.setReadOnly(True)
        self.selected_file_edit.setObjectName("selected_file_edit")
        self.horizontalLayout_15.addWidget(self.selected_file_edit)
        self.select_file_button = QtWidgets.QPushButton(self.frame_38)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_file_button.sizePolicy().hasHeightForWidth())
        self.select_file_button.setSizePolicy(sizePolicy)
        self.select_file_button.setObjectName("select_file_button")
        self.horizontalLayout_15.addWidget(self.select_file_button)
        self.verticalLayout_25.addWidget(self.frame_38)
        self.verticalLayout_13.addWidget(self.frame_18)
        self.frame_24 = QtWidgets.QFrame(self.frame_22)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setObjectName("frame_24")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_24)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.import_report_button = QtWidgets.QPushButton(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_report_button.sizePolicy().hasHeightForWidth())
        self.import_report_button.setSizePolicy(sizePolicy)
        self.import_report_button.setMaximumSize(QtCore.QSize(180, 16777215))
        self.import_report_button.setObjectName("import_report_button")
        self.gridLayout_7.addWidget(self.import_report_button, 0, 0, 1, 1)
        self.verticalLayout_13.addWidget(self.frame_24)
        self.horizontalLayout.addWidget(self.frame_22)

        self.retranslateUi(import_report_tab)
        QtCore.QMetaObject.connectSlotsByName(import_report_tab)

    def retranslateUi(self, import_report_tab):
        _translate = QtCore.QCoreApplication.translate
        import_report_tab.setWindowTitle(_translate("import_report_tab", "Import Report"))
        self.label_18.setText(_translate("import_report_tab", "Select Vendor"))
        self.label_17.setText(_translate("import_report_tab", "Select Report Type"))
        self.label_16.setText(_translate("import_report_tab", "Date"))
        self.label_19.setText(_translate("import_report_tab", "Report Year"))
        self.report_year_date_edit.setDisplayFormat(_translate("import_report_tab", "yyyy"))
        self.label_36.setText(_translate("import_report_tab", "Target Report File"))
        self.select_file_button.setText(_translate("import_report_tab", "Select File"))
        self.import_report_button.setText(_translate("import_report_tab", "Import Selected Report"))
