# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1000, 640)
        mainWindow.setMinimumSize(QtCore.QSize(1000, 640))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        mainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.manage_vendors_tab = QtWidgets.QWidget()
        self.manage_vendors_tab.setObjectName("manage_vendors_tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.manage_vendors_tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_12 = QtWidgets.QFrame(self.manage_vendors_tab)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.label_13)
        self.vendorsListView = QtWidgets.QListView(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.vendorsListView.setFont(font)
        self.vendorsListView.setAlternatingRowColors(True)
        self.vendorsListView.setObjectName("vendorsListView")
        self.verticalLayout_6.addWidget(self.vendorsListView)
        self.frame_2 = QtWidgets.QFrame(self.frame_12)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.addVendorButton = QtWidgets.QPushButton(self.frame_2)
        self.addVendorButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.addVendorButton.setObjectName("addVendorButton")
        self.gridLayout_3.addWidget(self.addVendorButton, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame_12)
        self.frame_8 = QtWidgets.QFrame(self.manage_vendors_tab)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_2 = QtWidgets.QVBoxLayout(self.frame_8)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_8)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.edit_vendor_details_frame = QtWidgets.QFrame(self.frame)
        self.edit_vendor_details_frame.setEnabled(False)
        self.edit_vendor_details_frame.setObjectName("edit_vendor_details_frame")
        self.formLayout = QtWidgets.QFormLayout(self.edit_vendor_details_frame)
        self.formLayout.setSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.nameEdit = QtWidgets.QLineEdit(self.edit_vendor_details_frame)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameEdit)
        self.label_2 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.customerIdEdit = QtWidgets.QLineEdit(self.edit_vendor_details_frame)
        self.customerIdEdit.setObjectName("customerIdEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.customerIdEdit)
        self.label_3 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.baseUrlEdit = QtWidgets.QLineEdit(self.edit_vendor_details_frame)
        self.baseUrlEdit.setObjectName("baseUrlEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.baseUrlEdit)
        self.label_4 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.requestorIdEdit = QtWidgets.QLineEdit(self.edit_vendor_details_frame)
        self.requestorIdEdit.setObjectName("requestorIdEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.requestorIdEdit)
        self.label_5 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.apiKeyEdit = QtWidgets.QLineEdit(self.edit_vendor_details_frame)
        self.apiKeyEdit.setObjectName("apiKeyEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.apiKeyEdit)
        self.label_6 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.platformEdit = QtWidgets.QLineEdit(self.edit_vendor_details_frame)
        self.platformEdit.setObjectName("platformEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.platformEdit)
        self.label_39 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label_39.setObjectName("label_39")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.local_only_check_box = QtWidgets.QCheckBox(self.edit_vendor_details_frame)
        self.local_only_check_box.setObjectName("local_only_check_box")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.local_only_check_box)
        self.label_28 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label_28.setObjectName("label_28")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.descriptionEdit = QtWidgets.QPlainTextEdit(self.edit_vendor_details_frame)
        self.descriptionEdit.setAutoFillBackground(False)
        self.descriptionEdit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.descriptionEdit.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.descriptionEdit.setTabChangesFocus(False)
        self.descriptionEdit.setPlainText("")
        self.descriptionEdit.setBackgroundVisible(False)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.descriptionEdit)
        self.companiesText = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.companiesText.setObjectName("companiesText")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.companiesText)
        self.companiesEdit = QtWidgets.QPlainTextEdit(self.edit_vendor_details_frame)
        self.companiesEdit.setObjectName("companiesEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.companiesEdit)
        self.verticalLayout.addWidget(self.edit_vendor_details_frame)
        self.edit_vendor_options_frame = QtWidgets.QFrame(self.frame)
        self.edit_vendor_options_frame.setEnabled(False)
        self.edit_vendor_options_frame.setObjectName("edit_vendor_options_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.edit_vendor_options_frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.saveVendorChangesButton = QtWidgets.QPushButton(self.edit_vendor_options_frame)
        self.saveVendorChangesButton.setDefault(False)
        self.saveVendorChangesButton.setFlat(False)
        self.saveVendorChangesButton.setObjectName("saveVendorChangesButton")
        self.horizontalLayout_5.addWidget(self.saveVendorChangesButton)
        self.undoVendorChangesButton = QtWidgets.QPushButton(self.edit_vendor_options_frame)
        self.undoVendorChangesButton.setObjectName("undoVendorChangesButton")
        self.horizontalLayout_5.addWidget(self.undoVendorChangesButton)
        self.removeVendorButton = QtWidgets.QPushButton(self.edit_vendor_options_frame)
        self.removeVendorButton.setObjectName("removeVendorButton")
        self.horizontalLayout_5.addWidget(self.removeVendorButton)
        self.verticalLayout.addWidget(self.edit_vendor_options_frame)
        self.horizontalLayout_2.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.frame_8)
        self.tabWidget.addTab(self.manage_vendors_tab, "")
        self.fetch_reports_tab = QtWidgets.QWidget()
        self.fetch_reports_tab.setObjectName("fetch_reports_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fetch_reports_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.fetch_reports_tab)
        self.frame_4.setMouseTracking(True)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_35 = QtWidgets.QLabel(self.frame_4)
        self.label_35.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_3.addWidget(self.label_35)
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setMinimumSize(QtCore.QSize(800, 60))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_28 = QtWidgets.QFrame(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_28.sizePolicy().hasHeightForWidth())
        self.frame_28.setSizePolicy(sizePolicy)
        self.frame_28.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_12.setSpacing(10)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_34 = QtWidgets.QLabel(self.frame_28)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_12.addWidget(self.label_34)
        self.All_reports_edit_fetch = QtWidgets.QDateEdit(self.frame_28)
        self.All_reports_edit_fetch.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.All_reports_edit_fetch.setObjectName("All_reports_edit_fetch")
        self.horizontalLayout_12.addWidget(self.All_reports_edit_fetch)
        self.horizontalLayout_10.addWidget(self.frame_28)
        self.fetch_all_data_button = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fetch_all_data_button.sizePolicy().hasHeightForWidth())
        self.fetch_all_data_button.setSizePolicy(sizePolicy)
        self.fetch_all_data_button.setMaximumSize(QtCore.QSize(300, 16777215))
        self.fetch_all_data_button.setObjectName("fetch_all_data_button")
        self.horizontalLayout_10.addWidget(self.fetch_all_data_button)
        self.verticalLayout_3.addWidget(self.frame_9)
        self.Adv_Fetch_text = QtWidgets.QLabel(self.frame_4)
        self.Adv_Fetch_text.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.Adv_Fetch_text.setFont(font)
        self.Adv_Fetch_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Adv_Fetch_text.setObjectName("Adv_Fetch_text")
        self.verticalLayout_3.addWidget(self.Adv_Fetch_text)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_10 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.horizontalFrame = QtWidgets.QFrame(self.frame_10)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.select_vendors_button_fetch = QtWidgets.QPushButton(self.horizontalFrame)
        self.select_vendors_button_fetch.setObjectName("select_vendors_button_fetch")
        self.horizontalLayout_4.addWidget(self.select_vendors_button_fetch)
        self.deselect_vendors_button_fetch = QtWidgets.QPushButton(self.horizontalFrame)
        self.deselect_vendors_button_fetch.setObjectName("deselect_vendors_button_fetch")
        self.horizontalLayout_4.addWidget(self.deselect_vendors_button_fetch)
        self.verticalLayout_4.addWidget(self.horizontalFrame)
        self.vendors_list_view_fetch = QtWidgets.QListView(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.vendors_list_view_fetch.setFont(font)
        self.vendors_list_view_fetch.setAlternatingRowColors(True)
        self.vendors_list_view_fetch.setObjectName("vendors_list_view_fetch")
        self.verticalLayout_4.addWidget(self.vendors_list_view_fetch)
        self.horizontalLayout_3.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.horizontalFrame_2 = QtWidgets.QFrame(self.frame_11)
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.select_report_types_button_fetch = QtWidgets.QPushButton(self.horizontalFrame_2)
        self.select_report_types_button_fetch.setObjectName("select_report_types_button_fetch")
        self.horizontalLayout_6.addWidget(self.select_report_types_button_fetch)
        self.deselect_report_types_button_fetch = QtWidgets.QPushButton(self.horizontalFrame_2)
        self.deselect_report_types_button_fetch.setObjectName("deselect_report_types_button_fetch")
        self.horizontalLayout_6.addWidget(self.deselect_report_types_button_fetch)
        self.toolButton = QtWidgets.QToolButton(self.horizontalFrame_2)
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_6.addWidget(self.toolButton)
        self.verticalLayout_5.addWidget(self.horizontalFrame_2)
        self.report_types_list_view = QtWidgets.QListView(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.report_types_list_view.setFont(font)
        self.report_types_list_view.setAlternatingRowColors(True)
        self.report_types_list_view.setObjectName("report_types_list_view")
        self.verticalLayout_5.addWidget(self.report_types_list_view)
        self.horizontalLayout_3.addWidget(self.frame_11)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_6 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setObjectName("frame_6")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_6)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setSpacing(20)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.begin_date_edit_fetch = QtWidgets.QDateEdit(self.frame_6)
        self.begin_date_edit_fetch.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.begin_date_edit_fetch.setObjectName("begin_date_edit_fetch")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.begin_date_edit_fetch)
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.end_date_edit_fetch = QtWidgets.QDateEdit(self.frame_6)
        self.end_date_edit_fetch.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.end_date_edit_fetch.setObjectName("end_date_edit_fetch")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.end_date_edit_fetch)
        self.verticalLayout_7.addWidget(self.frame_6)
        self.frame_13 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fetch_advanced_button = QtWidgets.QPushButton(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fetch_advanced_button.sizePolicy().hasHeightForWidth())
        self.fetch_advanced_button.setSizePolicy(sizePolicy)
        self.fetch_advanced_button.setMaximumSize(QtCore.QSize(180, 16777215))
        self.fetch_advanced_button.setObjectName("fetch_advanced_button")
        self.gridLayout_2.addWidget(self.fetch_advanced_button, 2, 1, 1, 1)
        self.save_checkbox = QtWidgets.QCheckBox(self.frame_13)
        self.save_checkbox.setObjectName("save_checkbox")
        self.gridLayout_2.addWidget(self.save_checkbox, 1, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_13)
        self.horizontalLayout_3.addWidget(self.frame_7)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.tabWidget.addTab(self.fetch_reports_tab, "")
        self.fetch_special_reports_tab = QtWidgets.QWidget()
        self.fetch_special_reports_tab.setObjectName("fetch_special_reports_tab")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.fetch_special_reports_tab)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_26 = QtWidgets.QFrame(self.fetch_special_reports_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_26.sizePolicy().hasHeightForWidth())
        self.frame_26.setSizePolicy(sizePolicy)
        self.frame_26.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_21 = QtWidgets.QLabel(self.frame_26)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_15.addWidget(self.label_21)
        self.frame_32 = QtWidgets.QFrame(self.frame_26)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.select_vendors_button_special = QtWidgets.QPushButton(self.frame_32)
        self.select_vendors_button_special.setObjectName("select_vendors_button_special")
        self.horizontalLayout_9.addWidget(self.select_vendors_button_special)
        self.deselect_vendors_button_special = QtWidgets.QPushButton(self.frame_32)
        self.deselect_vendors_button_special.setObjectName("deselect_vendors_button_special")
        self.horizontalLayout_9.addWidget(self.deselect_vendors_button_special)
        self.verticalLayout_15.addWidget(self.frame_32)
        self.vendors_list_view_special = QtWidgets.QListView(self.frame_26)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.vendors_list_view_special.setFont(font)
        self.vendors_list_view_special.setAlternatingRowColors(True)
        self.vendors_list_view_special.setObjectName("vendors_list_view_special")
        self.verticalLayout_15.addWidget(self.vendors_list_view_special)
        self.horizontalLayout_8.addWidget(self.frame_26)
        self.frame_25 = QtWidgets.QFrame(self.fetch_special_reports_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_25.sizePolicy().hasHeightForWidth())
        self.frame_25.setSizePolicy(sizePolicy)
        self.frame_25.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_20 = QtWidgets.QLabel(self.frame_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_14.addWidget(self.label_20)
        self.frame_30 = QtWidgets.QFrame(self.frame_25)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setObjectName("frame_30")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_30)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.ir_radio_button = QtWidgets.QRadioButton(self.frame_30)
        self.ir_radio_button.setObjectName("ir_radio_button")
        self.gridLayout_9.addWidget(self.ir_radio_button, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.tr_radio_button = QtWidgets.QRadioButton(self.frame_30)
        self.tr_radio_button.setObjectName("tr_radio_button")
        self.gridLayout_9.addWidget(self.tr_radio_button, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pr_radio_button = QtWidgets.QRadioButton(self.frame_30)
        self.pr_radio_button.setChecked(True)
        self.pr_radio_button.setObjectName("pr_radio_button")
        self.gridLayout_9.addWidget(self.pr_radio_button, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.dr_radio_button = QtWidgets.QRadioButton(self.frame_30)
        self.dr_radio_button.setObjectName("dr_radio_button")
        self.gridLayout_9.addWidget(self.dr_radio_button, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_14.addWidget(self.frame_30)
        self.horizontalLayout_8.addWidget(self.frame_25)
        self.frame_27 = QtWidgets.QFrame(self.fetch_special_reports_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_27.sizePolicy().hasHeightForWidth())
        self.frame_27.setSizePolicy(sizePolicy)
        self.frame_27.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.attributes_frame = QtWidgets.QFrame(self.frame_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attributes_frame.sizePolicy().hasHeightForWidth())
        self.attributes_frame.setSizePolicy(sizePolicy)
        self.attributes_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.attributes_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.attributes_frame.setObjectName("attributes_frame")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.attributes_frame)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_16.addWidget(self.attributes_frame)
        self.frame_31 = QtWidgets.QFrame(self.frame_27)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setObjectName("frame_31")
        self.formLayout_5 = QtWidgets.QFormLayout(self.frame_31)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_5.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_5.setSpacing(20)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_22 = QtWidgets.QLabel(self.frame_31)
        self.label_22.setObjectName("label_22")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.label_23 = QtWidgets.QLabel(self.frame_31)
        self.label_23.setObjectName("label_23")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.begin_date_edit_special = QtWidgets.QDateEdit(self.frame_31)
        self.begin_date_edit_special.setObjectName("begin_date_edit_special")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.begin_date_edit_special)
        self.end_date_edit_special = QtWidgets.QDateEdit(self.frame_31)
        self.end_date_edit_special.setObjectName("end_date_edit_special")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.end_date_edit_special)
        self.verticalLayout_16.addWidget(self.frame_31)
        self.frame_29 = QtWidgets.QFrame(self.frame_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_29.sizePolicy().hasHeightForWidth())
        self.frame_29.setSizePolicy(sizePolicy)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setObjectName("frame_29")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_29)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.fetch_special_data_button = QtWidgets.QPushButton(self.frame_29)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fetch_special_data_button.sizePolicy().hasHeightForWidth())
        self.fetch_special_data_button.setSizePolicy(sizePolicy)
        self.fetch_special_data_button.setMaximumSize(QtCore.QSize(180, 16777215))
        self.fetch_special_data_button.setObjectName("fetch_special_data_button")
        self.gridLayout_8.addWidget(self.fetch_special_data_button, 0, 0, 1, 1)
        self.verticalLayout_16.addWidget(self.frame_29)
        self.horizontalLayout_8.addWidget(self.frame_27)
        self.tabWidget.addTab(self.fetch_special_reports_tab, "")
        self.import_file_tab = QtWidgets.QWidget()
        self.import_file_tab.setObjectName("import_file_tab")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.import_file_tab)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_8 = QtWidgets.QLabel(self.import_file_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_21.addWidget(self.label_8)
        self.frame_3 = QtWidgets.QFrame(self.import_file_tab)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_21 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_21.sizePolicy().hasHeightForWidth())
        self.frame_21.setSizePolicy(sizePolicy)
        self.frame_21.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_18 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_12.addWidget(self.label_18)
        self.vendors_list_view_import = QtWidgets.QListView(self.frame_21)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.vendors_list_view_import.setFont(font)
        self.vendors_list_view_import.setAlternatingRowColors(True)
        self.vendors_list_view_import.setObjectName("vendors_list_view_import")
        self.verticalLayout_12.addWidget(self.vendors_list_view_import)
        self.horizontalLayout_11.addWidget(self.frame_21)
        self.frame_20 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_20.sizePolicy().hasHeightForWidth())
        self.frame_20.setSizePolicy(sizePolicy)
        self.frame_20.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_17 = QtWidgets.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_11.addWidget(self.label_17)
        self.report_types_list_view_import = QtWidgets.QListView(self.frame_20)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.report_types_list_view_import.setFont(font)
        self.report_types_list_view_import.setAlternatingRowColors(True)
        self.report_types_list_view_import.setObjectName("report_types_list_view_import")
        self.verticalLayout_11.addWidget(self.report_types_list_view_import)
        self.horizontalLayout_11.addWidget(self.frame_20)
        self.frame_22 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_22.sizePolicy().hasHeightForWidth())
        self.frame_22.setSizePolicy(sizePolicy)
        self.frame_22.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_23 = QtWidgets.QFrame(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_23.sizePolicy().hasHeightForWidth())
        self.frame_23.setSizePolicy(sizePolicy)
        self.frame_23.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setObjectName("frame_23")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frame_23)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_4.setSpacing(20)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_19 = QtWidgets.QLabel(self.frame_23)
        self.label_19.setMinimumSize(QtCore.QSize(100, 0))
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.report_year_date_edit = QtWidgets.QDateEdit(self.frame_23)
        self.report_year_date_edit.setObjectName("report_year_date_edit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.report_year_date_edit)
        self.select_file_button = QtWidgets.QPushButton(self.frame_23)
        self.select_file_button.setMinimumSize(QtCore.QSize(100, 0))
        self.select_file_button.setObjectName("select_file_button")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.select_file_button)
        self.selected_file_label = QtWidgets.QLabel(self.frame_23)
        self.selected_file_label.setMinimumSize(QtCore.QSize(100, 0))
        self.selected_file_label.setObjectName("selected_file_label")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.selected_file_label)
        self.verticalLayout_13.addWidget(self.frame_23)
        self.frame_24 = QtWidgets.QFrame(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_24.sizePolicy().hasHeightForWidth())
        self.frame_24.setSizePolicy(sizePolicy)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setObjectName("frame_24")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_24)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.import_file_button = QtWidgets.QPushButton(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_file_button.sizePolicy().hasHeightForWidth())
        self.import_file_button.setSizePolicy(sizePolicy)
        self.import_file_button.setMaximumSize(QtCore.QSize(180, 16777215))
        self.import_file_button.setObjectName("import_file_button")
        self.gridLayout_7.addWidget(self.import_file_button, 0, 0, 1, 1)
        self.verticalLayout_13.addWidget(self.frame_24)
        self.horizontalLayout_11.addWidget(self.frame_22)
        self.verticalLayout_21.addWidget(self.frame_3)
        self.tabWidget.addTab(self.import_file_tab, "")
        self.search_tab = QtWidgets.QWidget()
        self.search_tab.setObjectName("search_tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.search_tab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.search_parameters_frame = QtWidgets.QFrame(self.search_tab)
        self.search_parameters_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_parameters_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_parameters_frame.setObjectName("search_parameters_frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.search_parameters_frame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.search_initial_parameters_frame = QtWidgets.QFrame(self.search_parameters_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_initial_parameters_frame.sizePolicy().hasHeightForWidth())
        self.search_initial_parameters_frame.setSizePolicy(sizePolicy)
        self.search_initial_parameters_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_initial_parameters_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_initial_parameters_frame.setObjectName("search_initial_parameters_frame")
        self.gridLayout1 = QtWidgets.QGridLayout(self.search_initial_parameters_frame)
        self.gridLayout1.setObjectName("gridLayout1")
        self.search_start_year_parameter_label = QtWidgets.QLabel(self.search_initial_parameters_frame)
        self.search_start_year_parameter_label.setObjectName("search_start_year_parameter_label")
        self.gridLayout1.addWidget(self.search_start_year_parameter_label, 0, 1, 1, 1)
        self.search_report_parameter_combobox = QtWidgets.QComboBox(self.search_initial_parameters_frame)
        self.search_report_parameter_combobox.setObjectName("search_report_parameter_combobox")
        self.gridLayout1.addWidget(self.search_report_parameter_combobox, 2, 0, 1, 1)
        self.search_report_parameter_label = QtWidgets.QLabel(self.search_initial_parameters_frame)
        self.search_report_parameter_label.setObjectName("search_report_parameter_label")
        self.gridLayout1.addWidget(self.search_report_parameter_label, 0, 0, 1, 1)
        self.search_end_year_parameter_label = QtWidgets.QLabel(self.search_initial_parameters_frame)
        self.search_end_year_parameter_label.setObjectName("search_end_year_parameter_label")
        self.gridLayout1.addWidget(self.search_end_year_parameter_label, 0, 2, 1, 1)
        self.search_start_year_parameter_dateedit = QtWidgets.QDateEdit(self.search_initial_parameters_frame)
        self.search_start_year_parameter_dateedit.setObjectName("search_start_year_parameter_dateedit")
        self.gridLayout1.addWidget(self.search_start_year_parameter_dateedit, 2, 1, 1, 1)
        self.search_end_year_parameter_dateedit = QtWidgets.QDateEdit(self.search_initial_parameters_frame)
        self.search_end_year_parameter_dateedit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.search_end_year_parameter_dateedit.setObjectName("search_end_year_parameter_dateedit")
        self.gridLayout1.addWidget(self.search_end_year_parameter_dateedit, 2, 2, 1, 1)
        self.verticalLayout_10.addWidget(self.search_initial_parameters_frame)
        self.search_and_clause_parameters_scrollarea = QtWidgets.QScrollArea(self.search_parameters_frame)
        self.search_and_clause_parameters_scrollarea.setWidgetResizable(True)
        self.search_and_clause_parameters_scrollarea.setObjectName("search_and_clause_parameters_scrollarea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 858, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout_8 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout_8.setObjectName("formLayout_8")
        self.search_and_clause_parameters_scrollarea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_10.addWidget(self.search_and_clause_parameters_scrollarea)
        self.search_add_and_button = QtWidgets.QPushButton(self.search_parameters_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_add_and_button.sizePolicy().hasHeightForWidth())
        self.search_add_and_button.setSizePolicy(sizePolicy)
        self.search_add_and_button.setObjectName("search_add_and_button")
        self.verticalLayout_10.addWidget(self.search_add_and_button)
        self.verticalLayout_8.addWidget(self.search_parameters_frame)
        self.search_button = QtWidgets.QPushButton(self.search_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_button.sizePolicy().hasHeightForWidth())
        self.search_button.setSizePolicy(sizePolicy)
        self.search_button.setObjectName("search_button")
        self.verticalLayout_8.addWidget(self.search_button)
        self.tabWidget.addTab(self.search_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.settings_tab)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_37 = QtWidgets.QFrame(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_37.sizePolicy().hasHeightForWidth())
        self.frame_37.setSizePolicy(sizePolicy)
        self.frame_37.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_37.setObjectName("frame_37")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_37)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.frame_35 = QtWidgets.QFrame(self.frame_37)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_35.sizePolicy().hasHeightForWidth())
        self.frame_35.setSizePolicy(sizePolicy)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setObjectName("frame_35")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_35)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_26 = QtWidgets.QLabel(self.frame_35)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_20.addWidget(self.label_26, 0, QtCore.Qt.AlignHCenter)
        self.frame_36 = QtWidgets.QFrame(self.frame_35)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_36.sizePolicy().hasHeightForWidth())
        self.frame_36.setSizePolicy(sizePolicy)
        self.frame_36.setObjectName("frame_36")
        self.formLayout_7 = QtWidgets.QFormLayout(self.frame_36)
        self.formLayout_7.setHorizontalSpacing(50)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_27 = QtWidgets.QLabel(self.frame_36)
        self.label_27.setObjectName("label_27")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.save_location_edit_fetch_2 = QtWidgets.QLineEdit(self.frame_36)
        self.save_location_edit_fetch_2.setObjectName("save_location_edit_fetch_2")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.save_location_edit_fetch_2)
        self.verticalLayout_20.addWidget(self.frame_36)
        self.gridLayout_10.addWidget(self.frame_35, 1, 0, 1, 1)
        self.frame_33 = QtWidgets.QFrame(self.frame_37)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_33.sizePolicy().hasHeightForWidth())
        self.frame_33.setSizePolicy(sizePolicy)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_24 = QtWidgets.QLabel(self.frame_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_19.addWidget(self.label_24, 0, QtCore.Qt.AlignHCenter)
        self.frame_34 = QtWidgets.QFrame(self.frame_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_34.sizePolicy().hasHeightForWidth())
        self.frame_34.setSizePolicy(sizePolicy)
        self.frame_34.setObjectName("frame_34")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_34)
        self.gridLayout_11.setHorizontalSpacing(10)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.concurrent_vendors_help_button = QtWidgets.QPushButton(self.frame_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.concurrent_vendors_help_button.sizePolicy().hasHeightForWidth())
        self.concurrent_vendors_help_button.setSizePolicy(sizePolicy)
        self.concurrent_vendors_help_button.setMaximumSize(QtCore.QSize(25, 25))
        self.concurrent_vendors_help_button.setObjectName("concurrent_vendors_help_button")
        self.gridLayout_11.addWidget(self.concurrent_vendors_help_button, 7, 2, 1, 1)
        self.other_directory_button = QtWidgets.QPushButton(self.frame_34)
        self.other_directory_button.setObjectName("other_directory_button")
        self.gridLayout_11.addWidget(self.other_directory_button, 1, 2, 1, 1)
        self.other_directory_edit = QtWidgets.QLineEdit(self.frame_34)
        self.other_directory_edit.setReadOnly(True)
        self.other_directory_edit.setObjectName("other_directory_edit")
        self.gridLayout_11.addWidget(self.other_directory_edit, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frame_34)
        self.label_25.setObjectName("label_25")
        self.gridLayout_11.addWidget(self.label_25, 0, 0, 1, 1)
        self.yearly_directory_button = QtWidgets.QPushButton(self.frame_34)
        self.yearly_directory_button.setObjectName("yearly_directory_button")
        self.gridLayout_11.addWidget(self.yearly_directory_button, 0, 2, 1, 1)
        self.concurrent_reports_spin_box = QtWidgets.QSpinBox(self.frame_34)
        self.concurrent_reports_spin_box.setMaximum(999)
        self.concurrent_reports_spin_box.setObjectName("concurrent_reports_spin_box")
        self.gridLayout_11.addWidget(self.concurrent_reports_spin_box, 8, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.frame_34)
        self.label_32.setObjectName("label_32")
        self.gridLayout_11.addWidget(self.label_32, 8, 0, 1, 1)
        self.yearly_directory_edit = QtWidgets.QLineEdit(self.frame_34)
        self.yearly_directory_edit.setReadOnly(True)
        self.yearly_directory_edit.setObjectName("yearly_directory_edit")
        self.gridLayout_11.addWidget(self.yearly_directory_edit, 0, 1, 1, 1)
        self.concurrent_reports_help_button = QtWidgets.QPushButton(self.frame_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.concurrent_reports_help_button.sizePolicy().hasHeightForWidth())
        self.concurrent_reports_help_button.setSizePolicy(sizePolicy)
        self.concurrent_reports_help_button.setMaximumSize(QtCore.QSize(25, 25))
        self.concurrent_reports_help_button.setObjectName("concurrent_reports_help_button")
        self.gridLayout_11.addWidget(self.concurrent_reports_help_button, 8, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame_34)
        self.label_29.setObjectName("label_29")
        self.gridLayout_11.addWidget(self.label_29, 1, 0, 1, 1)
        self.yearly_directory_help_button = QtWidgets.QPushButton(self.frame_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yearly_directory_help_button.sizePolicy().hasHeightForWidth())
        self.yearly_directory_help_button.setSizePolicy(sizePolicy)
        self.yearly_directory_help_button.setMaximumSize(QtCore.QSize(25, 25))
        self.yearly_directory_help_button.setObjectName("yearly_directory_help_button")
        self.gridLayout_11.addWidget(self.yearly_directory_help_button, 0, 3, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.frame_34)
        self.label_33.setObjectName("label_33")
        self.gridLayout_11.addWidget(self.label_33, 10, 0, 1, 1)
        self.request_interval_help_button = QtWidgets.QPushButton(self.frame_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.request_interval_help_button.sizePolicy().hasHeightForWidth())
        self.request_interval_help_button.setSizePolicy(sizePolicy)
        self.request_interval_help_button.setMaximumSize(QtCore.QSize(25, 25))
        self.request_interval_help_button.setObjectName("request_interval_help_button")
        self.gridLayout_11.addWidget(self.request_interval_help_button, 5, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_34)
        self.label_30.setObjectName("label_30")
        self.gridLayout_11.addWidget(self.label_30, 5, 0, 1, 1)
        self.empty_cell_edit = QtWidgets.QLineEdit(self.frame_34)
        self.empty_cell_edit.setObjectName("empty_cell_edit")
        self.gridLayout_11.addWidget(self.empty_cell_edit, 10, 1, 1, 1)
        self.other_directory_help_button = QtWidgets.QPushButton(self.frame_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.other_directory_help_button.sizePolicy().hasHeightForWidth())
        self.other_directory_help_button.setSizePolicy(sizePolicy)
        self.other_directory_help_button.setMaximumSize(QtCore.QSize(25, 25))
        self.other_directory_help_button.setObjectName("other_directory_help_button")
        self.gridLayout_11.addWidget(self.other_directory_help_button, 1, 3, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.frame_34)
        self.label_31.setObjectName("label_31")
        self.gridLayout_11.addWidget(self.label_31, 7, 0, 1, 1)
        self.concurrent_vendors_spin_box = QtWidgets.QSpinBox(self.frame_34)
        self.concurrent_vendors_spin_box.setMaximum(999)
        self.concurrent_vendors_spin_box.setObjectName("concurrent_vendors_spin_box")
        self.gridLayout_11.addWidget(self.concurrent_vendors_spin_box, 7, 1, 1, 1)
        self.request_interval_spin_box = QtWidgets.QSpinBox(self.frame_34)
        self.request_interval_spin_box.setMaximum(999)
        self.request_interval_spin_box.setObjectName("request_interval_spin_box")
        self.gridLayout_11.addWidget(self.request_interval_spin_box, 5, 1, 1, 1)
        self.empty_cell_help_button = QtWidgets.QPushButton(self.frame_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.empty_cell_help_button.sizePolicy().hasHeightForWidth())
        self.empty_cell_help_button.setSizePolicy(sizePolicy)
        self.empty_cell_help_button.setMaximumSize(QtCore.QSize(25, 25))
        self.empty_cell_help_button.setObjectName("empty_cell_help_button")
        self.gridLayout_11.addWidget(self.empty_cell_help_button, 10, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.frame_34)
        self.label_37.setObjectName("label_37")
        self.gridLayout_11.addWidget(self.label_37, 6, 0, 1, 1)
        self.request_timeout_spin_box = QtWidgets.QSpinBox(self.frame_34)
        self.request_timeout_spin_box.setMaximum(9999)
        self.request_timeout_spin_box.setSingleStep(30)
        self.request_timeout_spin_box.setObjectName("request_timeout_spin_box")
        self.gridLayout_11.addWidget(self.request_timeout_spin_box, 6, 1, 1, 1)
        self.request_timeout_help_button = QtWidgets.QPushButton(self.frame_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.request_timeout_help_button.sizePolicy().hasHeightForWidth())
        self.request_timeout_help_button.setSizePolicy(sizePolicy)
        self.request_timeout_help_button.setMaximumSize(QtCore.QSize(25, 25))
        self.request_timeout_help_button.setObjectName("request_timeout_help_button")
        self.gridLayout_11.addWidget(self.request_timeout_help_button, 6, 2, 1, 1)
        self.verticalLayout_19.addWidget(self.frame_34)
        self.gridLayout_10.addWidget(self.frame_33, 0, 0, 1, 1)
        self.verticalLayout_17.addWidget(self.frame_37)
        self.tabWidget.addTab(self.settings_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_40 = QtWidgets.QLabel(self.tab)
        self.label_40.setGeometry(QtCore.QRect(30, 10, 946, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Libly"))
        self.label_13.setText(_translate("mainWindow", "Select Vendor"))
        self.addVendorButton.setText(_translate("mainWindow", "Add New Vendor"))
        self.label_7.setText(_translate("mainWindow", "Edit Vendor"))
        self.label.setText(_translate("mainWindow", "Name"))
        self.label_2.setText(_translate("mainWindow", "Customer ID"))
        self.label_3.setText(_translate("mainWindow", "Base URL"))
        self.label_4.setText(_translate("mainWindow", "Requestor ID"))
        self.label_5.setText(_translate("mainWindow", "API Key"))
        self.label_6.setText(_translate("mainWindow", "Platform"))
        self.label_39.setText(_translate("mainWindow", "Local Only Vendor"))
        self.label_28.setText(_translate("mainWindow", "Description"))
        self.companiesText.setText(_translate("mainWindow", "External Companies"))
        self.saveVendorChangesButton.setText(_translate("mainWindow", "Save Changes"))
        self.undoVendorChangesButton.setText(_translate("mainWindow", "Undo Changes"))
        self.removeVendorButton.setText(_translate("mainWindow", "Remove Vendor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.manage_vendors_tab), _translate("mainWindow", "Manage Vendors"))
        self.label_35.setText(_translate("mainWindow", "Fetch All Reports"))
        self.label_34.setText(_translate("mainWindow", "Year"))
        self.All_reports_edit_fetch.setDisplayFormat(_translate("mainWindow", "yyyy"))
        self.fetch_all_data_button.setText(_translate("mainWindow", "Fetch All Reports"))
        self.Adv_Fetch_text.setText(_translate("mainWindow", "Advanced Fetch Reports"))
        self.label_11.setText(_translate("mainWindow", "Select Vendors"))
        self.select_vendors_button_fetch.setText(_translate("mainWindow", "Select All"))
        self.deselect_vendors_button_fetch.setText(_translate("mainWindow", "Deselect All"))
        self.label_12.setText(_translate("mainWindow", "Select Report Types"))
        self.select_report_types_button_fetch.setText(_translate("mainWindow", "Select All"))
        self.deselect_report_types_button_fetch.setText(_translate("mainWindow", "Deselect All"))
        self.toolButton.setText(_translate("mainWindow", "?"))
        self.label_9.setText(_translate("mainWindow", "Begin Date"))
        self.begin_date_edit_fetch.setDisplayFormat(_translate("mainWindow", "yyyy-MM"))
        self.label_10.setText(_translate("mainWindow", "End Date"))
        self.end_date_edit_fetch.setDisplayFormat(_translate("mainWindow", "yyyy-MM"))
        self.fetch_advanced_button.setText(_translate("mainWindow", "Fetch Selected Reports"))
        self.save_checkbox.setText(_translate("mainWindow", "Save Elsewhere"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fetch_reports_tab), _translate("mainWindow", "Fetch Reports"))
        self.label_21.setText(_translate("mainWindow", "Select Vendors"))
        self.select_vendors_button_special.setText(_translate("mainWindow", "Select All"))
        self.deselect_vendors_button_special.setText(_translate("mainWindow", "Deselect All"))
        self.label_20.setText(_translate("mainWindow", "Select Report Type"))
        self.ir_radio_button.setText(_translate("mainWindow", "IR"))
        self.tr_radio_button.setText(_translate("mainWindow", "TR"))
        self.pr_radio_button.setText(_translate("mainWindow", "PR"))
        self.dr_radio_button.setText(_translate("mainWindow", "DR"))
        self.label_22.setText(_translate("mainWindow", "Begin Date"))
        self.label_23.setText(_translate("mainWindow", "End Date"))
        self.begin_date_edit_special.setDisplayFormat(_translate("mainWindow", "yyyy-MM"))
        self.end_date_edit_special.setDisplayFormat(_translate("mainWindow", "yyyy-MM"))
        self.fetch_special_data_button.setText(_translate("mainWindow", "Fetch Special Report"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fetch_special_reports_tab), _translate("mainWindow", "Fetch Special Reports"))
        self.label_8.setText(_translate("mainWindow", "PAGE IS IN DEVELOPMENT"))
        self.label_18.setText(_translate("mainWindow", "Select Vendor"))
        self.label_17.setText(_translate("mainWindow", "Select Report Type"))
        self.label_19.setText(_translate("mainWindow", "Report Year"))
        self.report_year_date_edit.setDisplayFormat(_translate("mainWindow", "yyyy"))
        self.select_file_button.setText(_translate("mainWindow", "Select File"))
        self.selected_file_label.setText(_translate("mainWindow", "None"))
        self.import_file_button.setText(_translate("mainWindow", "Import Selected File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.import_file_tab), _translate("mainWindow", "Import File"))
        self.search_start_year_parameter_label.setText(_translate("mainWindow", "Start Year"))
        self.search_report_parameter_label.setText(_translate("mainWindow", "Report"))
        self.search_end_year_parameter_label.setText(_translate("mainWindow", "End year"))
        self.search_start_year_parameter_dateedit.setDisplayFormat(_translate("mainWindow", "yyyy"))
        self.search_end_year_parameter_dateedit.setDisplayFormat(_translate("mainWindow", "yyyy"))
        self.search_add_and_button.setText(_translate("mainWindow", "Add \"And\" Clause"))
        self.search_button.setText(_translate("mainWindow", "Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.search_tab), _translate("mainWindow", "Search"))
        self.label_26.setText(_translate("mainWindow", "Search"))
        self.label_27.setText(_translate("mainWindow", "[In Development]"))
        self.save_location_edit_fetch_2.setText(_translate("mainWindow", "[In Development]"))
        self.label_24.setText(_translate("mainWindow", "Reports"))
        self.concurrent_vendors_help_button.setText(_translate("mainWindow", "?"))
        self.other_directory_button.setText(_translate("mainWindow", "Choose Folder..."))
        self.label_25.setText(_translate("mainWindow", "Yearly Reports Directory"))
        self.yearly_directory_button.setText(_translate("mainWindow", "Choose Folder..."))
        self.label_32.setText(_translate("mainWindow", "Concurrent Reports"))
        self.concurrent_reports_help_button.setText(_translate("mainWindow", "?"))
        self.label_29.setText(_translate("mainWindow", "Other Reports Directory"))
        self.yearly_directory_help_button.setText(_translate("mainWindow", "?"))
        self.label_33.setText(_translate("mainWindow", "Empty Cell"))
        self.request_interval_help_button.setText(_translate("mainWindow", "?"))
        self.label_30.setText(_translate("mainWindow", "Report Request Interval"))
        self.other_directory_help_button.setText(_translate("mainWindow", "?"))
        self.label_31.setText(_translate("mainWindow", "Concurrent Vendors"))
        self.empty_cell_help_button.setText(_translate("mainWindow", "?"))
        self.label_37.setText(_translate("mainWindow", "Request Timeout"))
        self.request_timeout_help_button.setText(_translate("mainWindow", "?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings_tab), _translate("mainWindow", "Settings"))
        self.label_40.setText(_translate("mainWindow", "PAGE IS IN DEVELOPMENT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "Visual"))

