# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManageVendorsTab.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_manage_vendors_tab(object):
    def setupUi(self, manage_vendors_tab):
        manage_vendors_tab.setObjectName("manage_vendors_tab")
        manage_vendors_tab.resize(803, 670)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ui/resources/tab_icons/manage_vendors_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        manage_vendors_tab.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(manage_vendors_tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_12 = QtWidgets.QFrame(manage_vendors_tab)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.label_13)
        self.vendorsListView = QtWidgets.QListView(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.vendorsListView.setFont(font)
        self.vendorsListView.setAlternatingRowColors(True)
        self.vendorsListView.setObjectName("vendorsListView")
        self.verticalLayout_6.addWidget(self.vendorsListView)
        self.frame_2 = QtWidgets.QFrame(self.frame_12)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.importVendorsButton = QtWidgets.QPushButton(self.frame_2)
        self.importVendorsButton.setObjectName("importVendorsButton")
        self.gridLayout_3.addWidget(self.importVendorsButton, 0, 1, 1, 1)
        self.addVendorButton = QtWidgets.QPushButton(self.frame_2)
        self.addVendorButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.addVendorButton.setObjectName("addVendorButton")
        self.gridLayout_3.addWidget(self.addVendorButton, 0, 0, 1, 1)
        self.exportVendorsButton = QtWidgets.QPushButton(self.frame_2)
        self.exportVendorsButton.setObjectName("exportVendorsButton")
        self.gridLayout_3.addWidget(self.exportVendorsButton, 0, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame_12)
        self.frame_8 = QtWidgets.QFrame(manage_vendors_tab)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_2 = QtWidgets.QVBoxLayout(self.frame_8)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_8)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.edit_vendor_details_frame = QtWidgets.QFrame(self.frame)
        self.edit_vendor_details_frame.setObjectName("edit_vendor_details_frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.edit_vendor_details_frame)
        self.gridLayout_5.setSpacing(20)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.baseUrlEdit = QtWidgets.QLineEdit(self.edit_vendor_details_frame)
        self.baseUrlEdit.setObjectName("baseUrlEdit")
        self.gridLayout_5.addWidget(self.baseUrlEdit, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 2, 0, 1, 1)
        self.name_validation_label = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.name_validation_label.setObjectName("name_validation_label")
        self.gridLayout_5.addWidget(self.name_validation_label, 1, 1, 1, 1)
        self.customerIdEdit = QtWidgets.QLineEdit(self.edit_vendor_details_frame)
        self.customerIdEdit.setObjectName("customerIdEdit")
        self.gridLayout_5.addWidget(self.customerIdEdit, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 8, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 9, 0, 1, 1)
        self.platformEdit = QtWidgets.QLineEdit(self.edit_vendor_details_frame)
        self.platformEdit.setObjectName("platformEdit")
        self.gridLayout_5.addWidget(self.platformEdit, 9, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 7, 0, 1, 1)
        self.nameEdit = QtWidgets.QLineEdit(self.edit_vendor_details_frame)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout_5.addWidget(self.nameEdit, 0, 1, 1, 1)
        self.apiKeyEdit = QtWidgets.QLineEdit(self.edit_vendor_details_frame)
        self.apiKeyEdit.setObjectName("apiKeyEdit")
        self.gridLayout_5.addWidget(self.apiKeyEdit, 8, 1, 1, 1)
        self.requestorIdEdit = QtWidgets.QLineEdit(self.edit_vendor_details_frame)
        self.requestorIdEdit.setObjectName("requestorIdEdit")
        self.gridLayout_5.addWidget(self.requestorIdEdit, 7, 1, 1, 1)
        self.companiesText = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.companiesText.setObjectName("companiesText")
        self.gridLayout_5.addWidget(self.companiesText, 12, 0, 1, 1, QtCore.Qt.AlignTop)
        self.label_39 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label_39.setObjectName("label_39")
        self.gridLayout_5.addWidget(self.label_39, 10, 0, 1, 1)
        self.companiesEdit = QtWidgets.QPlainTextEdit(self.edit_vendor_details_frame)
        self.companiesEdit.setObjectName("companiesEdit")
        self.gridLayout_5.addWidget(self.companiesEdit, 12, 1, 1, 1)
        self.descriptionEdit = QtWidgets.QPlainTextEdit(self.edit_vendor_details_frame)
        self.descriptionEdit.setAutoFillBackground(False)
        self.descriptionEdit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.descriptionEdit.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.descriptionEdit.setTabChangesFocus(False)
        self.descriptionEdit.setPlainText("")
        self.descriptionEdit.setBackgroundVisible(False)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.gridLayout_5.addWidget(self.descriptionEdit, 11, 1, 1, 1)
        self.local_only_check_box = QtWidgets.QCheckBox(self.edit_vendor_details_frame)
        self.local_only_check_box.setObjectName("local_only_check_box")
        self.gridLayout_5.addWidget(self.local_only_check_box, 10, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 11, 0, 1, 1, QtCore.Qt.AlignTop)
        self.url_validation_label = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.url_validation_label.setObjectName("url_validation_label")
        self.gridLayout_5.addWidget(self.url_validation_label, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.edit_vendor_details_frame)
        self.edit_vendor_options_frame = QtWidgets.QFrame(self.frame)
        self.edit_vendor_options_frame.setEnabled(False)
        self.edit_vendor_options_frame.setObjectName("edit_vendor_options_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.edit_vendor_options_frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.saveVendorChangesButton = QtWidgets.QPushButton(self.edit_vendor_options_frame)
        self.saveVendorChangesButton.setDefault(False)
        self.saveVendorChangesButton.setFlat(False)
        self.saveVendorChangesButton.setObjectName("saveVendorChangesButton")
        self.horizontalLayout_5.addWidget(self.saveVendorChangesButton)
        self.undoVendorChangesButton = QtWidgets.QPushButton(self.edit_vendor_options_frame)
        self.undoVendorChangesButton.setObjectName("undoVendorChangesButton")
        self.horizontalLayout_5.addWidget(self.undoVendorChangesButton)
        self.removeVendorButton = QtWidgets.QPushButton(self.edit_vendor_options_frame)
        self.removeVendorButton.setObjectName("removeVendorButton")
        self.horizontalLayout_5.addWidget(self.removeVendorButton)
        self.verticalLayout.addWidget(self.edit_vendor_options_frame)
        self.horizontalLayout_2.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.frame_8)

        self.retranslateUi(manage_vendors_tab)
        QtCore.QMetaObject.connectSlotsByName(manage_vendors_tab)
        manage_vendors_tab.setTabOrder(self.vendorsListView, self.addVendorButton)
        manage_vendors_tab.setTabOrder(self.addVendorButton, self.importVendorsButton)
        manage_vendors_tab.setTabOrder(self.importVendorsButton, self.exportVendorsButton)
        manage_vendors_tab.setTabOrder(self.exportVendorsButton, self.nameEdit)
        manage_vendors_tab.setTabOrder(self.nameEdit, self.baseUrlEdit)
        manage_vendors_tab.setTabOrder(self.baseUrlEdit, self.customerIdEdit)
        manage_vendors_tab.setTabOrder(self.customerIdEdit, self.requestorIdEdit)
        manage_vendors_tab.setTabOrder(self.requestorIdEdit, self.apiKeyEdit)
        manage_vendors_tab.setTabOrder(self.apiKeyEdit, self.platformEdit)
        manage_vendors_tab.setTabOrder(self.platformEdit, self.local_only_check_box)
        manage_vendors_tab.setTabOrder(self.local_only_check_box, self.descriptionEdit)
        manage_vendors_tab.setTabOrder(self.descriptionEdit, self.companiesEdit)
        manage_vendors_tab.setTabOrder(self.companiesEdit, self.saveVendorChangesButton)
        manage_vendors_tab.setTabOrder(self.saveVendorChangesButton, self.undoVendorChangesButton)
        manage_vendors_tab.setTabOrder(self.undoVendorChangesButton, self.removeVendorButton)

    def retranslateUi(self, manage_vendors_tab):
        _translate = QtCore.QCoreApplication.translate
        manage_vendors_tab.setWindowTitle(_translate("manage_vendors_tab", "Manage Vendors"))
        self.label_13.setText(_translate("manage_vendors_tab", "Select Vendor"))
        self.importVendorsButton.setText(_translate("manage_vendors_tab", "Import Vendors"))
        self.addVendorButton.setText(_translate("manage_vendors_tab", "Add New Vendor"))
        self.exportVendorsButton.setText(_translate("manage_vendors_tab", "Export Vendors"))
        self.label_7.setText(_translate("manage_vendors_tab", "Edit Vendor"))
        self.label_3.setText(_translate("manage_vendors_tab", "Base URL"))
        self.name_validation_label.setText(_translate("manage_vendors_tab", "Validation label"))
        self.label_5.setText(_translate("manage_vendors_tab", "API Key"))
        self.label_6.setText(_translate("manage_vendors_tab", "Platform"))
        self.label_2.setText(_translate("manage_vendors_tab", "Customer ID"))
        self.label.setText(_translate("manage_vendors_tab", "Name"))
        self.label_4.setText(_translate("manage_vendors_tab", "Requestor ID"))
        self.companiesText.setText(_translate("manage_vendors_tab", "External Companies"))
        self.label_39.setText(_translate("manage_vendors_tab", "Local Only Vendor"))
        self.label_28.setText(_translate("manage_vendors_tab", "Description"))
        self.url_validation_label.setText(_translate("manage_vendors_tab", "Validation label"))
        self.saveVendorChangesButton.setText(_translate("manage_vendors_tab", "Save Changes"))
        self.undoVendorChangesButton.setText(_translate("manage_vendors_tab", "Undo Changes"))
        self.removeVendorButton.setText(_translate("manage_vendors_tab", "Remove Vendor"))
import Resources_rc
