# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SearchTab.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_search_tab(object):
    def setupUi(self, search_tab):
        search_tab.setObjectName("search_tab")
        search_tab.resize(913, 578)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ui/resources/tab_icons/search_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        search_tab.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(search_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_parameters_frame = QtWidgets.QFrame(search_tab)
        self.search_parameters_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_parameters_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_parameters_frame.setObjectName("search_parameters_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.search_parameters_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.search_and_clause_parameters_scrollarea = QtWidgets.QScrollArea(self.search_parameters_frame)
        self.search_and_clause_parameters_scrollarea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.search_and_clause_parameters_scrollarea.setWidgetResizable(True)
        self.search_and_clause_parameters_scrollarea.setObjectName("search_and_clause_parameters_scrollarea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 778, 176))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout_8 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout_8.setObjectName("formLayout_8")
        self.search_and_clause_parameters_scrollarea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.search_and_clause_parameters_scrollarea, 4, 0, 1, 5)
        self.search_start_year_parameter_dateedit = QtWidgets.QDateEdit(self.search_parameters_frame)
        self.search_start_year_parameter_dateedit.setObjectName("search_start_year_parameter_dateedit")
        self.gridLayout_2.addWidget(self.search_start_year_parameter_dateedit, 3, 1, 1, 1)
        self.search_add_and_button = QtWidgets.QPushButton(self.search_parameters_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_add_and_button.sizePolicy().hasHeightForWidth())
        self.search_add_and_button.setSizePolicy(sizePolicy)
        self.search_add_and_button.setObjectName("search_add_and_button")
        self.gridLayout_2.addWidget(self.search_add_and_button, 3, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 3, 1, 1)
        self.search_report_parameter_combobox = QtWidgets.QComboBox(self.search_parameters_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_report_parameter_combobox.sizePolicy().hasHeightForWidth())
        self.search_report_parameter_combobox.setSizePolicy(sizePolicy)
        self.search_report_parameter_combobox.setObjectName("search_report_parameter_combobox")
        self.gridLayout_2.addWidget(self.search_report_parameter_combobox, 3, 0, 1, 1)
        self.search_report_parameter_label = QtWidgets.QLabel(self.search_parameters_frame)
        self.search_report_parameter_label.setObjectName("search_report_parameter_label")
        self.gridLayout_2.addWidget(self.search_report_parameter_label, 1, 0, 1, 1)
        self.search_start_year_parameter_label = QtWidgets.QLabel(self.search_parameters_frame)
        self.search_start_year_parameter_label.setObjectName("search_start_year_parameter_label")
        self.gridLayout_2.addWidget(self.search_start_year_parameter_label, 1, 1, 1, 1)
        self.search_end_year_parameter_label = QtWidgets.QLabel(self.search_parameters_frame)
        self.search_end_year_parameter_label.setObjectName("search_end_year_parameter_label")
        self.gridLayout_2.addWidget(self.search_end_year_parameter_label, 1, 2, 1, 1)
        self.search_end_year_parameter_dateedit = QtWidgets.QDateEdit(self.search_parameters_frame)
        self.search_end_year_parameter_dateedit.setObjectName("search_end_year_parameter_dateedit")
        self.gridLayout_2.addWidget(self.search_end_year_parameter_dateedit, 3, 2, 1, 1)
        self.verticalLayout.addWidget(self.search_parameters_frame)
        self.search_control_frame = QtWidgets.QFrame(search_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_control_frame.sizePolicy().hasHeightForWidth())
        self.search_control_frame.setSizePolicy(sizePolicy)
        self.search_control_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_control_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_control_frame.setObjectName("search_control_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.search_control_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.search_export_button = QtWidgets.QPushButton(self.search_control_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_export_button.sizePolicy().hasHeightForWidth())
        self.search_export_button.setSizePolicy(sizePolicy)
        self.search_export_button.setObjectName("search_export_button")
        self.gridLayout.addWidget(self.search_export_button, 1, 0, 1, 1)
        self.search_button = QtWidgets.QPushButton(self.search_control_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_button.sizePolicy().hasHeightForWidth())
        self.search_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.search_button.setFont(font)
        self.search_button.setObjectName("search_button")
        self.gridLayout.addWidget(self.search_button, 0, 3, 2, 1)
        self.search_import_button = QtWidgets.QPushButton(self.search_control_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_import_button.sizePolicy().hasHeightForWidth())
        self.search_import_button.setSizePolicy(sizePolicy)
        self.search_import_button.setObjectName("search_import_button")
        self.gridLayout.addWidget(self.search_import_button, 0, 0, 1, 1)
        self.search_open_file_checkbox = QtWidgets.QCheckBox(self.search_control_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_open_file_checkbox.sizePolicy().hasHeightForWidth())
        self.search_open_file_checkbox.setSizePolicy(sizePolicy)
        self.search_open_file_checkbox.setChecked(True)
        self.search_open_file_checkbox.setTristate(False)
        self.search_open_file_checkbox.setObjectName("search_open_file_checkbox")
        self.gridLayout.addWidget(self.search_open_file_checkbox, 0, 2, 1, 1)
        self.search_open_folder_checkbox = QtWidgets.QCheckBox(self.search_control_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_open_folder_checkbox.sizePolicy().hasHeightForWidth())
        self.search_open_folder_checkbox.setSizePolicy(sizePolicy)
        self.search_open_folder_checkbox.setObjectName("search_open_folder_checkbox")
        self.gridLayout.addWidget(self.search_open_folder_checkbox, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 2, 1)
        self.verticalLayout.addWidget(self.search_control_frame)

        self.retranslateUi(search_tab)
        QtCore.QMetaObject.connectSlotsByName(search_tab)

    def retranslateUi(self, search_tab):
        _translate = QtCore.QCoreApplication.translate
        search_tab.setWindowTitle(_translate("search_tab", "Search"))
        self.search_start_year_parameter_dateedit.setDisplayFormat(_translate("search_tab", "yyyy"))
        self.search_add_and_button.setText(_translate("search_tab", "Add \"And\""))
        self.search_report_parameter_label.setText(_translate("search_tab", "Report"))
        self.search_start_year_parameter_label.setText(_translate("search_tab", "Start Year"))
        self.search_end_year_parameter_label.setText(_translate("search_tab", "End year"))
        self.search_end_year_parameter_dateedit.setDisplayFormat(_translate("search_tab", "yyyy"))
        self.search_export_button.setText(_translate("search_tab", "Export Search"))
        self.search_button.setText(_translate("search_tab", "Search"))
        self.search_import_button.setText(_translate("search_tab", "Import Search"))
        self.search_open_file_checkbox.setText(_translate("search_tab", "Open File"))
        self.search_open_folder_checkbox.setText(_translate("search_tab", "Open Folder"))

import Resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    search_tab = QtWidgets.QWidget()
    ui = Ui_search_tab()
    ui.setupUi(search_tab)
    search_tab.show()
    sys.exit(app.exec_())

