# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SearchTab.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_search_tab(object):
    def setupUi(self, search_tab):
        search_tab.setObjectName("search_tab")
        search_tab.resize(934, 725)
        self.verticalLayout = QtWidgets.QVBoxLayout(search_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_parameters_frame = QtWidgets.QFrame(search_tab)
        self.search_parameters_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_parameters_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_parameters_frame.setObjectName("search_parameters_frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.search_parameters_frame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.search_initial_parameters_frame = QtWidgets.QFrame(self.search_parameters_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_initial_parameters_frame.sizePolicy().hasHeightForWidth())
        self.search_initial_parameters_frame.setSizePolicy(sizePolicy)
        self.search_initial_parameters_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_initial_parameters_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_initial_parameters_frame.setObjectName("search_initial_parameters_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.search_initial_parameters_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.search_start_year_parameter_label = QtWidgets.QLabel(self.search_initial_parameters_frame)
        self.search_start_year_parameter_label.setObjectName("search_start_year_parameter_label")
        self.gridLayout.addWidget(self.search_start_year_parameter_label, 0, 1, 1, 1)
        self.search_report_parameter_combobox = QtWidgets.QComboBox(self.search_initial_parameters_frame)
        self.search_report_parameter_combobox.setObjectName("search_report_parameter_combobox")
        self.gridLayout.addWidget(self.search_report_parameter_combobox, 2, 0, 1, 1)
        self.search_report_parameter_label = QtWidgets.QLabel(self.search_initial_parameters_frame)
        self.search_report_parameter_label.setObjectName("search_report_parameter_label")
        self.gridLayout.addWidget(self.search_report_parameter_label, 0, 0, 1, 1)
        self.search_end_year_parameter_label = QtWidgets.QLabel(self.search_initial_parameters_frame)
        self.search_end_year_parameter_label.setObjectName("search_end_year_parameter_label")
        self.gridLayout.addWidget(self.search_end_year_parameter_label, 0, 2, 1, 1)
        self.search_start_year_parameter_dateedit = QtWidgets.QDateEdit(self.search_initial_parameters_frame)
        self.search_start_year_parameter_dateedit.setObjectName("search_start_year_parameter_dateedit")
        self.gridLayout.addWidget(self.search_start_year_parameter_dateedit, 2, 1, 1, 1)
        self.search_end_year_parameter_dateedit = QtWidgets.QDateEdit(self.search_initial_parameters_frame)
        self.search_end_year_parameter_dateedit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.search_end_year_parameter_dateedit.setObjectName("search_end_year_parameter_dateedit")
        self.gridLayout.addWidget(self.search_end_year_parameter_dateedit, 2, 2, 1, 1)
        self.verticalLayout_10.addWidget(self.search_initial_parameters_frame)
        self.search_and_clause_parameters_scrollarea = QtWidgets.QScrollArea(self.search_parameters_frame)
        self.search_and_clause_parameters_scrollarea.setWidgetResizable(True)
        self.search_and_clause_parameters_scrollarea.setObjectName("search_and_clause_parameters_scrollarea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 842, 223))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout_8 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout_8.setObjectName("formLayout_8")
        self.search_and_clause_parameters_scrollarea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_10.addWidget(self.search_and_clause_parameters_scrollarea)
        self.search_add_and_button = QtWidgets.QPushButton(self.search_parameters_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_add_and_button.sizePolicy().hasHeightForWidth())
        self.search_add_and_button.setSizePolicy(sizePolicy)
        self.search_add_and_button.setObjectName("search_add_and_button")
        self.verticalLayout_10.addWidget(self.search_add_and_button)
        self.verticalLayout.addWidget(self.search_parameters_frame)
        self.search_control_frame = QtWidgets.QFrame(search_tab)
        self.search_control_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_control_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_control_frame.setObjectName("search_control_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.search_control_frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.search_import_button = QtWidgets.QPushButton(self.search_control_frame)
        self.search_import_button.setObjectName("search_import_button")
        self.gridLayout_4.addWidget(self.search_import_button, 3, 2, 1, 1)
        self.search_button = QtWidgets.QPushButton(self.search_control_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_button.sizePolicy().hasHeightForWidth())
        self.search_button.setSizePolicy(sizePolicy)
        self.search_button.setObjectName("search_button")
        self.gridLayout_4.addWidget(self.search_button, 2, 1, 1, 2)
        self.search_export_button = QtWidgets.QPushButton(self.search_control_frame)
        self.search_export_button.setObjectName("search_export_button")
        self.gridLayout_4.addWidget(self.search_export_button, 3, 1, 1, 1)
        self.open_file_radioButton = QtWidgets.QRadioButton(self.search_control_frame)
        self.open_file_radioButton.setChecked(True)
        self.open_file_radioButton.setObjectName("open_file_radioButton")
        self.gridLayout_4.addWidget(self.open_file_radioButton, 2, 3, 1, 1)
        self.open_folder_radioButton = QtWidgets.QRadioButton(self.search_control_frame)
        self.open_folder_radioButton.setObjectName("open_folder_radioButton")
        self.gridLayout_4.addWidget(self.open_folder_radioButton, 2, 4, 1, 1)
        self.open_both_radioButton = QtWidgets.QRadioButton(self.search_control_frame)
        self.open_both_radioButton.setObjectName("open_both_radioButton")
        self.gridLayout_4.addWidget(self.open_both_radioButton, 3, 3, 1, 1)
        self.dont_open_radioButton = QtWidgets.QRadioButton(self.search_control_frame)
        self.dont_open_radioButton.setObjectName("dont_open_radioButton")
        self.gridLayout_4.addWidget(self.dont_open_radioButton, 3, 4, 1, 1)
        self.verticalLayout.addWidget(self.search_control_frame)

        self.retranslateUi(search_tab)
        QtCore.QMetaObject.connectSlotsByName(search_tab)

    def retranslateUi(self, search_tab):
        _translate = QtCore.QCoreApplication.translate
        search_tab.setWindowTitle(_translate("search_tab", "Search"))
        self.search_start_year_parameter_label.setText(_translate("search_tab", "Start Year"))
        self.search_report_parameter_label.setText(_translate("search_tab", "Report"))
        self.search_end_year_parameter_label.setText(_translate("search_tab", "End year"))
        self.search_start_year_parameter_dateedit.setDisplayFormat(_translate("search_tab", "yyyy"))
        self.search_end_year_parameter_dateedit.setDisplayFormat(_translate("search_tab", "yyyy"))
        self.search_add_and_button.setText(_translate("search_tab", "Add \"And\" Clause"))
        self.search_import_button.setText(_translate("search_tab", "Import Search"))
        self.search_button.setText(_translate("search_tab", "Search"))
        self.search_export_button.setText(_translate("search_tab", "Export Search"))
        self.open_file_radioButton.setText(_translate("search_tab", "Open File"))
        self.open_folder_radioButton.setText(_translate("search_tab", "Open Folder"))
        self.open_both_radioButton.setText(_translate("search_tab", "Open Both"))
        self.dont_open_radioButton.setText(_translate("search_tab", "Don\'t Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    search_tab = QtWidgets.QWidget()
    ui = Ui_search_tab()
    ui.setupUi(search_tab)
    search_tab.show()
    sys.exit(app.exec_())

